export interface CountryData {
  name: string;
  code: string;
  flag: string;
  provinces: Record<string, string[]>;
}

export const WORLD_COUNTRIES: Record<string, CountryData> = {
  espana: {
    name: "España",
    code: "ES",
    flag: "🇪🇸",
    provinces: {
      "Álava": ["Vitoria-Gasteiz", "Amurrio", "Llodio"],
      "Albacete": ["Albacete", "Hellín", "Almansa", "Villarrobledo"],
      "Alicante": ["Alicante", "Elche", "Torrevieja", "Benidorm", "Alcoi", "Elda"],
      "Almería": ["Almería", "Roquetas de Mar", "El Ejido", "Níjar"],
      "Asturias": ["Gijón", "Oviedo", "Avilés", "Mieres", "Langreo"],
      "Ávila": ["Ávila", "Arévalo", "Arenas de San Pedro"],
      "Badajoz": ["Badajoz", "Mérida", "Don Benito", "Almendralejo", "Zafra"],
      "Baleares": ["Palma de Mallorca", "Ibiza", "San Antonio", "Manacor", "Ciutadella", "Mahón"],
      "Barcelona": ["Barcelona", "Hospitalet", "Badalona", "Terrassa", "Sabadell", "Mataró", "Sitges", "Castelldefels"],
      "Burgos": ["Burgos", "Miranda de Ebro", "Aranda de Duero"],
      "Cáceres": ["Cáceres", "Plasencia", "Navalmoral de la Mata"],
      "Cádiz": ["Cádiz", "Jerez de la Frontera", "Algeciras", "San Fernando", "El Puerto de Santa María", "Chiclana"],
      "Cantabria": ["Santander", "Torrelavega", "Castro-Urdiales", "Camargo"],
      "Castellón": ["Castellón de la Plana", "Villarreal", "Burriana", "Vinaroz"],
      "Ciudad Real": ["Ciudad Real", "Puertollano", "Tomelloso", "Alcázar de San Juan", "Valdepeñas"],
      "Córdoba": ["Córdoba", "Lucena", "Puente Genil", "Montilla"],
      "La Coruña": ["La Coruña", "Santiago de Compostela", "Ferrol", "Narón", "Oleiros"],
      "Cuenca": ["Cuenca", "Tarancón", "Quintanar del Rey"],
      "Gerona": ["Gerona", "Figueras", "Lloret de Mar", "Blanes", "Olot"],
      "Granada": ["Granada", "Motril", "Almuñécar", "Baza", "Loja"],
      "Guadalajara": ["Guadalajara", "Azuqueca de Henares", "Alovera"],
      "Guipúzcoa": ["San Sebastián", "Irún", "Rentería", "Éibar", "Zarauz"],
      "Huelva": ["Huelva", "Lepe", "Almonte", "Moguer"],
      "Huesca": ["Huesca", "Barbastro", "Monzón", "Jaca"],
      "Jaén": ["Jaén", "Linares", "Andújar", "Úbeda", "Martos"],
      "León": ["León", "Ponferrada", "San Andrés del Rabanedo"],
      "Lérida": ["Lérida", "Balaguer", "Tárrega", "Mollerussa"],
      "Lugo": ["Lugo", "Monforte de Lemos", "Vivero", "Vilalba"],
      "Madrid": ["Madrid", "Móstoles", "Alcalá de Henares", "Fuenlabrada", "Leganés", "Getafe", "Alcobendas", "Pozuelo"],
      "Málaga": ["Málaga", "Marbella", "Mijas", "Fuengirola", "Torremolinos", "Estepona", "Benalmádena", "Ronda"],
      "Murcia": ["Murcia", "Cartagena", "Lorca", "Molina de Segura", "Águilas"],
      "Navarra": ["Pamplona", "Tudela", "Barañáin", "Estella"],
      "Orense": ["Orense", "Carballino", "Verín", "Barco de Valdeorras"],
      "Palencia": ["Palencia", "Aguilar de Campoo", "Guardo"],
      "Las Palmas": ["Las Palmas de Gran Canaria", "Telde", "Arrecife", "Puerto del Rosario", "Mogán"],
      "Pontevedra": ["Vigo", "Pontevedra", "Vilagarcía de Arousa", "Redondela"],
      "La Rioja": ["Logroño", "Calahorra", "Arnedo", "Haro"],
      "Salamanca": ["Salamanca", "Béjar", "Ciudad Rodrigo"],
      "Santa Cruz de Tenerife": ["Santa Cruz de Tenerife", "San Cristóbal de La Laguna", "Arona", "Adeje", "Puerto de la Cruz"],
      "Segovia": ["Segovia", "El Espinar", "Cuéllar"],
      "Sevilla": ["Sevilla", "Dos Hermanas", "Alcalá de Guadaíra", "Utrera", "Écija"],
      "Soria": ["Soria", "Almazán", "Burgo de Osma"],
      "Tarragona": ["Tarragona", "Reus", "Tortosa", "Vendrell", "Salou"],
      "Teruel": ["Teruel", "Alcañiz", "Andorra"],
      "Toledo": ["Toledo", "Talavera de la Reina", "Illescas", "Seseña"],
      "Valencia": ["Valencia", "Torrente", "Gandía", "Paterna", "Sagunto", "Alcira", "Mislata", "Burjasot"],
      "Valladolid": ["Valladolid", "Laguna de Duero", "Medina del Campo"],
      "Vizcaya": ["Bilbao", "Baracaldo", "Getxo", "Portugalete", "Santurce", "Basauri"],
      "Zamora": ["Zamora", "Benavente", "Toro"],
      "Zaragoza": ["Zaragoza", "Calatayud", "Utebo", "Ejea de los Caballeros"]
    }
  },
  ecuador: {
    name: "Ecuador",
    code: "EC",
    flag: "🇪🇨",
    provinces: {
      "Azuay": ["Cuenca", "Gualaceo", "Paute", "Santa Isabel", "Girón", "Chordeleg"],
      "Bolívar": ["Guaranda", "San Miguel", "Chimbo", "Echeandía", "Caluma"],
      "Cañar": ["Azogues", "Cañar", "La Troncal", "Biblián", "El Tambo"],
      "Carchi": ["Tulcán", "San Gabriel", "El Ángel", "Huaca", "Mira"],
      "Chimborazo": ["Riobamba", "Alausí", "Guano", "Chambo", "Colta", "Cumandá"],
      "Cotopaxi": ["Latacunga", "Pujilí", "Salcedo", "La Maná", "Saquisilí", "Sigchos"],
      "El Oro": ["Machala", "Pasaje", "Santa Rosa", "Huaquillas", "Arenillas", "Piñas", "Zaruma", "El Guabo"],
      "Esmeraldas": ["Esmeraldas", "Atacames", "Quinindé", "San Lorenzo", "Muisne", "Río Verde"],
      "Galápagos": ["Puerto Ayora", "Puerto Baquerizo Moreno", "Puerto Villamil"],
      "Guayas": ["Guayaquil", "Samborondón", "Durán", "Milagro", "Daule", "Playas", "Empalme", "Naranjal", "Balzar", "Yaguachi"],
      "Imbabura": ["Ibarra", "Otavalo", "Cotacachi", "Atuntaqui", "Pimampiro", "Urcuquí"],
      "Loja": ["Loja", "Catamayo", "Cariamanga", "Macará", "Catacocha", "Saraguro", "Alamor", "Celica"],
      "Los Ríos": ["Babahoyo", "Quevedo", "Ventanas", "Vinces", "Buena Fe", "Puebloviejo", "Mocache", "Urdaneta"],
      "Manabí": ["Manta", "Portoviejo", "Chone", "Montecristi", "Bahía de Caráquez", "El Carmen", "Jipijapa", "Pedernales", "Calceta", "Sucre"],
      "Morona Santiago": ["Macas", "Gualaquiza", "Sucúa", "Limón Indanza", "Santiago", "Palora"],
      "Napo": ["Tena", "Archidona", "El Chaco", "Baeza", "Carlos Julio Arosemena Tola"],
      "Orellana": ["Puerto Francisco de Orellana (Coca)", "La Joya de los Sachas", "Loreto", "Nuevo Rocafuerte"],
      "Pastaza": ["Puyo", "Mera", "Santa Clara", "Arajuno"],
      "Pichincha": ["Quito", "Sangolquí", "Cayambe", "Machachi", "Tabacundo", "San Miguel de los Bancos", "Pedro Vicente Maldonado", "Puerto Quito"],
      "Santa Elena": ["Santa Elena", "Salinas", "La Libertad", "Manglaralto", "Montañita"],
      "Santo Domingo de los Tsáchilas": ["Santo Domingo", "La Concordia", "Alluriquín"],
      "Sucumbíos": ["Nueva Loja (Lago Agrio)", "Shushufindi", "El Dorado de Cascales", "Lumbaqui", "Tarapoa"],
      "Tungurahua": ["Ambato", "Baños", "Pelileo", "Píllaro", "Quero", "Cevallos", "Mocha", "Tisaleo"],
      "Zamora Chinchipe": ["Zamora", "Yantzaza", "El Pangui", "Zumba", "Guayzimi"]
    }
  },
  colombia: {
    name: "Colombia",
    code: "CO",
    flag: "🇨🇴",
    provinces: {
      "Antioquia": ["Medellín", "Envigado", "Itagüí", "Bello", "Rionegro", "Apartadó"],
      "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Puerto Colombia"],
      "Bogotá D.C.": ["Bogotá"],
      "Bolívar": ["Cartagena", "Magangué", "Turbaco"],
      "Valle del Cauca": ["Cali", "Palmira", "Buenaventura", "Tuluá", "Buga", "Cartago"],
      "Santander": ["Bucaramanga", "Floridablanca", "Girón", "Barrancabermeja"],
      "Cundinamarca": ["Soacha", "Chía", "Zipaquirá", "Facatativá", "Fusagasugá"],
      "Nariño": ["Pasto", "Ipiales", "Tumaco"],
      "Magdalena": ["Santa Marta", "Ciénaga", "Fundación"],
      "Norte de Santander": ["Cúcuta", "Ocaña", "Villa del Rosario", "Pamplona"],
      "Tolima": ["Ibagué", "Espinal", "Melgar"],
      "Risaralda": ["Pereira", "Dosquebradas", "Santa Rosa de Cabal"],
      "Quindío": ["Armenia", "Calarcá", "Tebaida"],
      "Caldas": ["Manizales", "Chinchiná", "La Dorada"],
      "Huila": ["Neiva", "Pitalito", "Garzón"],
      "Meta": ["Villavicencio", "Acacías", "Granada"],
      "Cesar": ["Valledupar", "Aguachica", "Codazzi"],
      "Córdoba": ["Montería", "Cereté", "Lorica", "Sahagún"],
      "Sucre": ["Sincelejo", "Corozal", "San Marcos"],
      "Boyacá": ["Tunja", "Sogamoso", "Duitama", "Chiquinquirá"],
      "Cauca": ["Popayán", "Santander de Quilichao", "Puerto Tejada"],
      "La Guajira": ["Riohacha", "Maicao", "Uribia"],
      "Chocó": ["Quibdó", "Istmina", "Bahía Solano"],
      "Casanare": ["Yopal", "Aguazul", "Paz de Ariporo"],
      "Caquetá": ["Florencia", "San Vicente del Caguán"],
      "Putumayo": ["Mocoa", "Puerto Asís", "Orito"],
      "Arauca": ["Arauca", "Tame", "Saravena"],
      "San Andrés": ["San Andrés", "Providencia"],
      "Amazonas": ["Leticia"],
      "Guaviare": ["San José del Guaviare"],
      "Vaupés": ["Mitú"],
      "Vichada": ["Puerto Carreño"],
      "Guainía": ["Inírida"]
    }
  },
  mexico: {
    name: "México",
    code: "MX",
    flag: "🇲🇽",
    provinces: {
      "Ciudad de México": ["CDMX", "Coyoacán", "Polanco", "La Condesa", "Tlalpan", "Iztapalapa"],
      "Jalisco": ["Guadalajara", "Zapopan", "Puerto Vallarta", "Tlaquepaque", "Tonalá"],
      "Nuevo León": ["Monterrey", "San Pedro Garza García", "San Nicolás", "Guadalupe", "Apodaca"],
      "Estado de México": ["Toluca", "Ecatepec", "Naucalpan", "Tlalnepantla", "Nezahualcóyotl", "Metepec"],
      "Quintana Roo": ["Cancún", "Playa del Carmen", "Tulum", "Cozumel", "Chetumal"],
      "Yucatán": ["Mérida", "Valladolid", "Progreso", "Tizimín"],
      "Puebla": ["Puebla", "Cholula", "Tehuacán", "Atlixco"],
      "Veracruz": ["Veracruz", "Xalapa", "Coatzacoalcos", "Boca del Río", "Orizaba"],
      "Guanajuato": ["Leon", "Irapuato", "Celaya", "Guanajuato", "San Miguel de Allende"],
      "Querétaro": ["Querétaro", "San Juan del Río", "Corregidora"],
      "Sinaloa": ["Culiacán", "Mazatlán", "Los Mochis"],
      "Baja California": ["Tijuana", "Mexicali", "Ensenada", "Rosarito"],
      "Baja California Sur": ["Cabo San Lucas", "San José del Cabo", "La Paz"],
      "Chihuahua": ["Chihuahua", "Ciudad Juárez", "Delicias"],
      "Coahuila": ["Saltillo", "Torreón", "Monclova"],
      "Sonora": ["Hermosillo", "Ciudad Obregón", "Nogales", "Guaymas"],
      "Michoacán": ["Morelia", "Uruapan", "Lázaro Cárdenas"],
      "Guerrero": ["Acapulco", "Chilpancingo", "Zihuatanejo", "Taxco"],
      "Oaxaca": ["Oaxaca de Juárez", "Huatulco", "Puerto Escondido"],
      "Chiapas": ["Tuxtla Gutiérrez", "San Cristóbal de las Casas", "Tapachula"],
      "Tabasco": ["Villahermosa", "Cárdenas"],
      "Tamaulipas": ["Reynosa", "Heroica Matamoros", "Nuevo Laredo", "Tampico"],
      "San Luis Potosí": ["San Luis Potosí", "Ciudad Valles", "Matehuala"],
      "Morelos": ["Cuernavaca", "Jiutepec", "Cuautla"],
      "Aguascalientes": ["Aguascalientes"],
      "Durango": ["Durango", "Gómez Palacio"],
      "Zacatecas": ["Zacatecas", "Fresnillo"],
      "Hidalgo": ["Pachuca", "Tulancingo", "Tula"],
      "Nayarit": ["Tepic", "Nuevo Vallarta"],
      "Colima": ["Colima", "Manzanillo"],
      "Tlaxcala": ["Tlaxcala", "Apizaco"],
      "Campeche": ["Campeche", "Ciudad del Carmen"]
    }
  },
  usa: {
    name: "Estados Unidos",
    code: "US",
    flag: "🇺🇸",
    provinces: {
      "California": ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento"],
      "New York": ["New York City", "Buffalo", "Rochester", "Syracuse", "Albany"],
      "Florida": ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale", "Key West"],
      "Texas": ["Houston", "Austin", "Dallas", "San Antonio", "El Paso", "Fort Worth"],
      "Nevada": ["Las Vegas", "Reno", "Henderson", "Carson City"],
      "Illinois": ["Chicago", "Aurora", "Naperville", "Rockford"],
      "Washington": ["Seattle", "Spokane", "Tacoma", "Bellevue"],
      "Georgia": ["Atlanta", "Savannah", "Augusta"],
      "Massachusetts": ["Boston", "Worcester", "Cambridge"],
      "Pennsylvania": ["Philadelphia", "Pittsburgh", "Allentown"],
      "Arizona": ["Phoenix", "Tucson", "Mesa", "Scottsdale"],
      "Colorado": ["Denver", "Colorado Springs", "Boulder"],
      "Oregon": ["Portland", "Eugene", "Salem"],
      "Hawaii": ["Honolulu", "Kailua", "Hilo"],
      "New Jersey": ["Newark", "Jersey City", "Trenton", "Atlantic City"],
      "North Carolina": ["Charlotte", "Raleigh", "Greensboro"],
      "Ohio": ["Columbus", "Cleveland", "Cincinnati"],
      "Michigan": ["Detroit", "Grand Rapids", "Lansing"],
      "Virginia": ["Virginia Beach", "Richmond", "Norfolk"],
      "Tennessee": ["Nashville", "Memphis", "Knoxville"],
      "Indiana": ["Indianapolis", "Fort Wayne"],
      "Missouri": ["Kansas City", "St. Louis"],
      "Wisconsin": ["Milwaukee", "Madison"],
      "Minnesota": ["Minneapolis", "St. Paul"],
      "Maryland": ["Baltimore", "Annapolis"],
      "South Carolina": ["Charleston", "Columbia"],
      "Alabama": ["Birmingham", "Montgomery"],
      "Louisiana": ["New Orleans", "Baton Rouge"],
      "Kentucky": ["Louisville", "Lexington"],
      "Oklahoma": ["Oklahoma City", "Tulsa"],
      "Utah": ["Salt Lake City", "Provo"],
      "Kansas": ["Wichita", "Overland Park"],
      "Iowa": ["Des Moines", "Cedar Rapids"],
      "Arkansas": ["Little Rock"],
      "Mississippi": ["Jackson"],
      "Connecticut": ["Bridgeport", "Hartford", "New Haven"],
      "New Mexico": ["Albuquerque", "Santa Fe"],
      "Nebraska": ["Omaha", "Lincoln"],
      "West Virginia": ["Charleston"],
      "Idaho": ["Boise"],
      "Hawaii_": ["Honolulu"],
      "New Hampshire": ["Manchester"],
      "Maine": ["Portland"],
      "Rhode Island": ["Providence"],
      "Delaware": ["Wilmington"],
      "South Dakota": ["Sioux Falls"],
      "North Dakota": ["Fargo"],
      "Montana": ["Billings"],
      "Vermont": ["Burlington"],
      "Wyoming": ["Cheyenne"],
      "Alaska": ["Anchorage"]
    }
  },
  argentina: {
    name: "Argentina",
    code: "AR",
    flag: "🇦🇷",
    provinces: {
      "Capital Federal": ["Buenos Aires"],
      "Buenos Aires Prov.": ["La Plata", "Mar del Plata", "Bahía Blanca", "Tandil", "Quilmes", "Pilar"],
      "Córdoba": ["Córdoba", "Villa Carlos Paz", "Río Cuarto", "Villa María"],
      "Santa Fe": ["Rosario", "Santa Fe", "Rafaela", "Venado Tuerto"],
      "Mendoza": ["Mendoza", "San Rafael", "Godoy Cruz"],
      "Tucumán": ["San Miguel de Tucumán", "Yerba Buena"],
      "Salta": ["Salta", "San Ramón de la Nueva Orán"],
      "Misiones": ["Posadas", "Puerto Iguazú", "Oberá"],
      "Chubut": ["Comodoro Rivadavia", "Puerto Madryn", "Trelew"],
      "Río Negro": ["San Carlos de Bariloche", "Viedma", "Cipolletti"],
      "Neuquén": ["Neuquén", "San Martín de los Andes"],
      "Entre Ríos": ["Paraná", "Concordia", "Gualeguaychú"],
      "Corrientes": ["Corrientes", "Goya", "Paso de los Libres"],
      "Chaco": ["Resistencia", "Presidencia Roque Sáenz Peña"],
      "Santiago del Estero": ["Santiago del Estero", "La Banda"],
      "San Juan": ["San Juan", "Chimbas"],
      "Jujuy": ["San Salvador de Jujuy", "San Pedro"],
      "San Luis": ["San Luis", "Villa Mercedes"],
      "Formosa": ["Formosa", "Clorinda"],
      "La Pampa": ["Santa Rosa", "General Pico"],
      "La Rioja": ["La Rioja", "Chilecito"],
      "Catamarca": ["San Fernando del Valle de Catamarca"],
      "Santa Cruz": ["Río Gallegos", "El Calafate"],
      "Tierra del Fuego": ["Ushuaia", "Río Grande"]
    }
  },
  peru: {
    name: "Perú",
    code: "PE",
    flag: "🇵🇪",
    provinces: {
      "Lima": ["Lima", "Miraflores", "San Isidro", "Barranco", "Ate", "Huacho", "Cañete"],
      "Arequipa": ["Arequipa", "Mollendo", "Camaná"],
      "La Libertad": ["Trujillo", "Huanchaco", "Pacasmayo"],
      "Lambayeque": ["Chiclayo", "Lambayeque", "Ferreñafe"],
      "Piura": ["Piura", "Sullana", "Talara", "Máncora", "Paita"],
      "Ancash": ["Chimbote", "Huaraz", "Caraz"],
      "Cusco": ["Cusco", "Urubamba", "Sicuani"],
      "Ica": ["Ica", "Chincha Alta", "Nazca", "Pisco"],
      "Junín": ["Huancayo", "Jauja", "Chanchamayo", "Tarma"],
      "Loreto": ["Iquitos", "Yurimaguas", "Nauta"],
      "San Martín": ["Tarapoto", "Moyobamba", "Juanjuí"],
      "Cajamarca": ["Cajamarca", "Jaén", "Chota"],
      "Puno": ["Puno", "Juliaca", "Ayaviri"],
      "Tacna": ["Tacna"],
      "Callao": ["Callao", "Bellavista", "La Punta"],
      "Huánuco": ["Huánuco", "Tingo María"],
      "Ayacucho": ["Ayacucho", "Huanta"],
      "Huancavelica": ["Huancavelica"],
      "Apurímac": ["Abancay", "Andahuaylas"],
      "Pasco": ["Cerro de Pasco", "Oxapampa"],
      "Tumbes": ["Tumbes", "Zarumilla"],
      "Ucayali": ["Pucallpa"],
      "Madre de Dios": ["Puerto Maldonado"],
      "Moquegua": ["Moquegua", "Ilo"],
      "Amazonas": ["Chachapoyas", "Bagua"],
    }
  },
  venezuela: {
    name: "Venezuela",
    code: "VE",
    flag: "🇻🇪",
    provinces: {
      "Distrito Capital": ["Caracas"],
      "Zulia": ["Maracaibo", "Cabimas", "Ciudad Ojeda", "San Francisco"],
      "Miranda": ["Chacao", "Baruta", "Los Teques", "Guatire", "Guarenas"],
      "Carabobo": ["Valencia", "Puerto Cabello", "Guacara", "Naguanagua"],
      "Lara": ["Barquisimeto", "Cabudare", "Carora"],
      "Aragua": ["Maracay", "La Victoria", "Turmero"],
      "Anzoátegui": ["Puerto La Cruz", "Barcelona", "El Tigre", "Anaco"],
      "Bolívar": ["Ciudad Guayana", "Ciudad Bolívar", "Upata"],
      "Táchira": ["San Cristóbal", "Táriba", "Rubio"],
      "Mérida": ["Mérida", "El Vigía", "Ejido"],
      "Nueva Esparta": ["Porlamar", "Pampatar", "La Asunción"],
      "Falcón": ["Punto Fijo", "Coro", "Tucacas"],
      "Sucre": ["Cumaná", "Carúpano"],
      "Monagas": ["Maturín"],
      "Guárico": ["San Juan de los Morros", "Valle de la Pascua", "Calabozo"],
      "Barinas": ["Barinas"],
      "Portuguesa": ["Acarigua", "Guanare"],
      "Trujillo": ["Valera", "Trujillo", "Boconó"],
      "Yaracuy": ["San Felipe", "Yaritagua"],
      "Cojedes": ["San Carlos"],
      "Apure": ["San Fernando de Apure"],
      "Delta Amacuro": ["Tucupita"],
      "Amazonas": ["Puerto Ayacucho"],
      "Vargas": ["La Guaira", "Catia La Mar", "Maiquetía"]
    }
  },
  chile: {
    name: "Chile",
    code: "CL",
    flag: "🇨🇱",
    provinces: {
      "Región Metropolitana": ["Santiago", "Providencia", "Las Condes", "Maipú", "Ñuñoa", "Puente Alto"],
      "Valparaíso": ["Valparaíso", "Viña del Mar", "Quilpué", "Villa Alemana", "San Antonio"],
      "Biobío": ["Concepción", "Talcahuano", "Los Ángeles", "Chiguayante"],
      "Antofagasta": ["Antofagasta", "Calama", "Tocopilla"],
      "Coquimbo": ["La Serena", "Coquimbo", "Ovalle"],
      "Araucanía": ["Temuco", "Padre Las Casas", "Angol"],
      "Los Lagos": ["Puerto Montt", "Osorno", "Castro"],
      "Tarapacá": ["Iquique", "Alto Hospicio"],
      "Atacama": ["Copiapó", "Vallenar"],
      "O'Higgins": ["Rancagua", "San Fernando", "Pichilemu"],
      "Maule": ["Talca", "Curicó", "Linares"],
      "Ñuble": ["Chillán", "San Carlos"],
      "Los Ríos": ["Valdivia", "La Unión"],
      "Aysén": ["Coyhaique", "Puerto Aysén"],
      "Magallanes": ["Punta Arenas", "Puerto Natales"],
      "Arica y Parinacota": ["Arica"]
    }
  },
  otros: {
    name: "Otro País (Global)",
    code: "GLOBAL",
    flag: "🌍",
    provinces: {
      "Internacional": ["Internacional", "Online", "Viajero"]
    }
  }
};
